[package]
name = "aw-tui-test"
version = "0.1.0"
edition = "2021"

[dependencies]
aw-tui = { path = "../aw-tui" }
aw-test-scenarios = { path = "../aw-test-scenarios" }
aw-rest-client-mock = { path = "../aw-rest-client-mock" }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
tokio = { workspace = true, features = ["full", "test-util"] }

[[bin]]
name = "tui-test"
path = "src/main.rs"
