name: AgentHarbor
options:
  bundleIdPrefix: com.agentfs
  deploymentTarget:
    macOS: 15.4
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  usesTabs: false

targets:
  AgentHarbor:
    type: application
    platform: macOS
    sources:
      - path: AgentHarbor
        excludes:
          - "*.storyboard"
          - "*.xcassets"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.agentfs.AgentHarbor
        CODE_SIGN_ENTITLEMENTS: AgentHarbor/AgentHarbor.entitlements
        LIBRARY_SEARCH_PATHS: ["$(PROJECT_DIR)/libs"]
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/../Frameworks"]
        MACOSX_DEPLOYMENT_TARGET: 15.4
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
          SWIFT_COMPILATION_MODE: wholemodule
    postCompileScripts:
      - script: |
          # Copy the pre-built extension to the expected location
          EXTENSION_PATH="../../../adapters/macos/xcode/AgentFSKitExtension/AgentFSKitExtension.appex"
          if [ -d "$EXTENSION_PATH" ]; then
            mkdir -p "${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}/Contents/PlugIns/"
            cp -R "$EXTENSION_PATH" "${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}/Contents/PlugIns/"
          else
            echo "Warning: Extension not found at $EXTENSION_PATH"
          fi
        name: Copy Extension to App Bundle


schemes:
  AgentHarbor:
    build:
      targets:
        AgentHarbor: all
    run:
      config: Debug
    archive:
      config: Release
