[package]
name = "aw-test-scenarios"
version = "0.1.0"
edition = "2021"

[dependencies]
aw-rest-api-contract = { path = "../aw-rest-api-contract" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }


