#!/usr/bin/env bash

echo "Executing Codex Setup"

apt-get update
apt-get install -y --no-install-recommends \
  git \
  fossil \
  mercurial \
  just \
  ruby-full \
  ruby-dev \
  zfsutils-linux \
  btrfs-progs \
  build-essential \
  pkg-config \
  libyaml-dev \
  libffi-dev \
  libxml2-dev \
  libxslt-dev \
  libgmp-dev \
  libssl-dev \
  libreadline-dev

sudo gem install rubocop
