[package]
name = "sandbox-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
nix = { version = "0.27", features = ["mount", "fs"] }

[dev-dependencies]
tempfile = { workspace = true }
