[workspace]

[package]
name = "agentfs-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "net", "io-util", "fs", "macros"] }
anyhow = "1.0"
libc = "0.2"
agentfs-core = { path = "../../../crates/agentfs-core" }
agentfs-proto = { path = "../../../crates/agentfs-proto" }
ethereum_ssz = "0.8"
ethereum_ssz_derive = "0.8"
