[workspace]

[package]
name = "agentfs-rust-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
lazy_static = "1.4"
ctor = "0.2"
redhook = "2.0"
agentfs-core = { path = "../../../crates/agentfs-core" }
agentfs-proto = { path = "../../../crates/agentfs-proto" }
ethereum_ssz = "0.8"
ethereum_ssz_derive = "0.8"
