[package]
name = "aw-rest-client-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
aw-client-api = { path = "../aw-client-api" }
aw-test-scenarios = { path = "../aw-test-scenarios" }
aw-rest-api-contract = { path = "../aw-rest-api-contract" }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }


