[package]
name = "sandbox-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
nix = { version = "0.27", features = [
  "sched",
  "mount",
  "user",
  "process",
  "fs",
] }

[dev-dependencies]
tempfile = { workspace = true }
