name: CI

on:
  push:
    branches: [ main, linux-sandbox ]
  pull_request:
    branches: [ main, linux-sandbox ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Check code formatting
      run: cargo fmt --all --check

    - name: Check code with clippy
      run: cargo clippy --workspace -- -D warnings

    - name: Check compilation
      run: cargo check --workspace

    - name: Run tests
      run: cargo test --workspace --verbose

    - name: Build sandbox helper binary
      run: cargo build --release --bin sbx-helper

  legacy-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install dependencies
      run: |
        gem install bundler
        cd legacy/ruby && bundle install

    - name: Run legacy tests
      run: |
        just legacy-test